### ISSUE TITLE
Templates for unit tests, tutorials and benchmarks (and maybe even the new SpineOpt structure)

### ISSUE THREAD

**Issue by tarskul** [spine-tools/SpineOpt.jl#744]
In the near future we would like to put some effort in a new structure for the unit tests (#733), add new tutorials (#735) and even benchmark SpineOpt together with other energy system modelling tools. To coordinate these tasks, it would be nice to have some templates for some possible energy systems. The idea is somewhat related to the idea of ArcheTypes we had before (#384). Although here (at first) we will focus on creating json files with the setup for a few energy systems.

The templates should cover most of the SpineOpt features as well as a few basic energy systems that can be build upon in unit tests or for users to get started with.

Currently only the SpineOpt data structure template is available from code (i.e. SpineOpt.template()) but we would also like to make the new templates available through such a command (e.g. keyword arguments for model templates and system templates or simply a list of templates to apply).

There is already some of that functionality there and we can consider some of these parts as optional as we can simply create a json file whenever we need one.

- [ ] (optional) Make json files for templates such that there are some basic starting points
- [x] Make json files for tutorials
- [x] Allow SpineOpt to use those json files in the unit tests
- [ ] (optional) Make one bigger json file with alternatives such that the unit tests can use the same json file with different (sub)systems

**Comment by clizbe** [comment]
@tarskul Can you please change this issue into an epic and detail a list of singular tasks we need to accomplish? Then we can convert those bullets into achievable issues as we see fit. Take a look at other epic issues to see what I mean.

**Comment by tarskul** [comment]
Some of the functionality is already implemented and some of it we could consider to be optional. We can close it for now and revisit it another time if so desired.
